### ISSUE TITLE
Segmentation fault (core dumped) error

### ISSUE THREAD

**Issue by pico-jp** [masashitsubaki/QuantumDeepField_molecule#2]
リポをclone後、デフォルト設定のまま $ bash train.sh したところ、
以下のエラーが出ました。
学習は走っているようですが、どうやらDataLoader周りでcrushしてしまっています。
ぜひこちらのコードを研究で活用させていただきたいのですが、手詰まりになってしまいました。
もし回避方法などあれば、ご教示いただけますと幸いです。

当方の実行環境は AWS (p2.xlarge) + Deep Learning AMI (Ubuntu 18.04) + RDKit です。
https://aws.amazon.com/marketplace/pp/B07Y43P7X5#pdp-overview

```
The code uses a GPU.
--------------------------------------------------
# of training samples:  34
# of validation samples:  4
# of test samples:  5
--------------------------------------------------
Set a QDF model.
# of model parameters: 392562
--------------------------------------------------
Start training of the QDF model with QM9under7atoms_atomizationenergy_eV dataset.
The training result is displayed in this terminal every epoch.
The result, prediction, and trained model are saved in the output directory.
Wait for a while...
The training will finish in about 0 hours 26 minutes.
--------------------------------------------------
Epoch	Time(sec)	Loss_E	Loss_V	MAE_val(eV)	MAE_test(eV)
0	0.8071885499994096	6209.085266113281	404.9622917175293	22.261384963989258	24.396270751953125
1	1.4956756869996752	5485.979797363281	392.7659606933594	20.992084503173828	23.13214683532715
2	2.175580770999659	4863.696319580078	386.9701862335205	19.829853057861328	21.962018966674805
3	2.8557513050000125	4676.126617431641	394.4252738952637	19.19409942626953	21.30068016052246
4	3.5467280840002786	4598.614196777344	386.27272605895996	20.13705062866211	22.27927589416504
5	4.246754251000311	5112.2559814453125	379.0389823913574	20.89983558654785	23.086027145385742
6	4.942768633000014	5517.936248779297	373.1512336730957	22.083404541015625	24.299663543701172
free(): invalid size
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/torch_mi_apr21/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 986, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/home/ubuntu/anaconda3/envs/torch_mi_apr21/lib/python3.7/queue.py", line 179, in get
    self.not_empty.wait(remaining)
  File "/home/ubuntu/anaconda3/envs/torch_mi_apr21/lib/python3.7/threading.py", line 300, in wait
    gotit = waiter.acquire(True, timeout)
  File "/home/ubuntu/anaconda3/envs/torch_mi_apr21/lib/python3.7/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 17362) is killed by signal: Aborted. 

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "train.py", line 389, in <module>
    MAE_val = tester.test(dataloader_val)[0]
  File "train.py", line 217, in test
    N = sum([len(data[0]) for data in dataloader])
  File "train.py", line 217, in <listcomp>
    N = sum([len(data[0]) for data in dataloader])
  File "/home/ubuntu/anaconda3/envs/torch_mi_apr21/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/home/ubuntu/anaconda3/envs/torch_mi_apr21/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1182, in _next_data
    idx, data = self._get_data()
  File "/home/ubuntu/anaconda3/envs/torch_mi_apr21/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1138, in _get_data
    success, data = self._try_get_data()
  File "/home/ubuntu/anaconda3/envs/torch_mi_apr21/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 999, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str)) from e
RuntimeError: DataLoader worker (pid(s) 17362) exited unexpectedly
train.sh: line 39: 16905 Segmentation fault      (core dumped) python train.py $dataset $basis_set $radius $grid_interval $dim $layer_functional $hidden_HK $layer_HK $operation $batch_size $lr $lr_decay $step_size $iteration $setting $num_workers

```

**Comment by masashitsubaki** [comment]
私の環境でそのようなエラーが出たことは一度もないので、ちょっとわからないですね…
ちょっと調べてみましたらこのようなものが見つかりましたが、関係ありますでしょうか？
https://github.com/pytorch/pytorch/issues/54716
https://github.com/pytorch/pytorch/issues/31758

**Comment by pico-jp** [comment]
ご丁寧にありがとうございます。当方でも連休中に調べてみます。
続報あればフィードバックさせていただきますね。

**Comment by pico-jp** [comment]
ありがとうございます。お陰様で、segmentation faultを回避できました。
方法としては、同じAWSのベースイメージを使って、
condaの仮想環境をpy37ベース→py36ベースに変更することで上手くいきました。

結局、種々の記事を参照したところ、このエラー (torchのDataLoader周りでのsegmentation fault) に対しては
明確な回避策はなく、CUDAやPythonライブラリの微妙なバージョンの食べ合わせが問題のようでした。
そこで、とりあえず違う環境でトライしてみたところ、案の定回避できた…という感じです。

上でご報告した際は、6 epoch目で落ちてしまっていましたが、
今回は以下の通り、デフォルト設定の2000 epoch回りきりました。(この挙動は正しそうでしょうか？)

```
1990	1051.6182371379982	0.08758403217507293	2.678808346390724	0.6708683967590332	0.31262245774269104
1991	1052.151659591007	0.09299542231383384	2.598832130432129	0.6705276966094971	0.3122425079345703
1992	1052.6745553590008	0.08780545338231605	2.608838066458702	0.6702039241790771	0.31190988421440125
1993	1053.1958858839935	0.09488449082709849	2.578882411122322	0.670478105545044	0.3122219145298004
1994	1053.7177461029933	0.09291976376698585	2.542456492781639	0.6711602210998535	0.31292954087257385
1995	1054.2471450209996	0.088944683666341	2.505008742213249	0.6725316047668457	0.31439706683158875
1996	1054.7733058449958	0.09380933306965744	2.6118716448545456	0.6716561317443848	0.3134639859199524
1997	1055.3024745230068	0.09384515730198473	2.5459655076265335	0.6699705123901367	0.3116420805454254
1998	1055.8249817869946	0.09495243363198824	2.569802865386009	0.6707282066345215	0.3125320374965668
1999	1056.3548852319946	0.09285446151625365	2.4770247787237167	0.6697218418121338	0.31136971712112427
```

なお、椿さんにご配布いただいております他のGNNのコードについても
類似の問題が起こっておりましたが、そちらも新しい環境にすることで無事計算が動き出しました。
(現在、molecularGNN_smilesを学習中です。)

**Comment by masashitsubaki** [comment]
回避できたようで良かったです。
私のPythonやPyTorchの環境は少し前のものを使っているので（最新のものだといつも手こずるので…）、
最新の環境だとそれに依存したエラーが出てしまうのかもしれません。

挙動については、まず回れば大丈夫ですが、
train.shで設定されているデータセット"QM9under7atoms_atomizationenergy_eV"は、
READMEに書いてあるようにトライアル（お試し）データセットです。
https://github.com/masashitsubaki/QuantumDeepField_molecule#usage
ターミナルに表示されているように、# of training samples: 34、つまり学習データが34サンプルしかありません。

別のデータセットで学習を回す際には、train.shのハイパーパラメータを設定し直す必要があります。
データセットやモデルのサイズに依存してけっこう変わると思いますし、
機械学習における最適化の知識や経験も必要なので、そのあたりはご自身で頑張っていただくしかないかもしれません。

よろしくお願いします。
